In [1]:
import os
import pandas as pd
from pathlib import Path
import shutil

In [2]:
# load dataset specification files (based on Manifold Bias paper)

calibration_real = pd.read_excel("calibration_real_paths.xlsx")
test_generated = pd.read_excel("test_generated_paths.xlsx")
test_real = pd.read_excel("test_real_paths.xlsx")

## CNNSpot
filtering relevant images from CNNSpot

### Real

In [23]:
CNNSpot_real = test_real[test_real["dataset name"] == "CNNSpot"].copy()

length_CNNSpot_real = len(CNNSpot_real)

length_CNNSpot_real

26088

In [24]:
CNNSpot_real.head()

                                path dataset name
3   train2/airplane/0_real/00928.png      CNNSpot
4        train2/cow/0_real/00758.png      CNNSpot
13      train2/sofa/0_real/00370.png      CNNSpot
14      train2/bird/0_real/00033.png      CNNSpot
20       train2/bus/0_real/01214.png      CNNSpot

In [25]:
split_CNNSpot_real = CNNSpot_real["path"].str.split(pat="/", expand=True)

# drop filename (last column)
split_CNNSpot_real = split_CNNSpot_real.iloc[:, :-1]

# optionally name the levels
split_CNNSpot_real.columns = [f"level_{i}" for i in range(split_CNNSpot_real.shape[1])]

# count per level and store in dict
level_counts = {
    col: split_CNNSpot_real[col].value_counts()
    for col in split_CNNSpot_real.columns
}

# print nicely sorted by level
for level, counts in level_counts.items():
    print(f"\n=== {level} ===")
    print(counts)

=== level_0 ===
level_0
train2     24920
backup2     1168
Name: count, dtype: int64

=== level_1 ===
level_1
bottle         1317
sofa           1312
person         1311
cat            1311
sheep          1310
car            1310
bicycle        1310
tvmonitor      1309
cow            1309
horse          1307
boat           1307
airplane       1304
train          1301
dog            1301
chair          1298
diningtable    1297
bird           1297
pottedplant    1296
motorbike      1292
bus            1289
Name: count, dtype: int64

=== level_2 ===
level_2
0_real    26088
Name: count, dtype: int64

In [26]:
splitted_CNNSpot_real = CNNSpot_real["path"].str.split(pat="/")
CNNSpot_real["real_path"] = ("CNNSpot/train/" + splitted_CNNSpot_real.str[1]+ "/" + splitted_CNNSpot_real.str[2]+ "/" + splitted_CNNSpot_real.str[3])

In [27]:
root = Path("../../datasets/")

CNNSpot_real["exists"] = [
    (root / p).exists() for p in CNNSpot_real["real_path"]
]

print(CNNSpot_real["exists"].value_counts()) # results mean that all file paths exist, within the CNNSpot folder

exists
False    26088
Name: count, dtype: int64

In [28]:
duplicates_CNN_real = CNNSpot_real.real_path[CNNSpot_real.real_path.duplicated()]
(f"Number of duplicate paths: {len(duplicates_CNN_real)}")

'Number of duplicate paths: 18'

In [29]:
src_root = Path("../../datasets")      # where files currently are
dst_root = Path("../../replication_datasets")   # where you want them

for rel_path in CNNSpot_real["real_path"]:
    src = src_root / rel_path
    dst = dst_root / rel_path

    if src.exists():
        dst.parent.mkdir(parents=True, exist_ok=True)  # create folders
        shutil.copy2(src, dst)  # preserves metadata
    else:
        print(f"Missing: {src}")

Missing: ../../datasets/CNNSpot/train/airplane/0_real/00928.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00758.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00370.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00033.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/01214.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/01288.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00575.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00367.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00246.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00705.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00307.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/01325.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00334.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/00028.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00498.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/01080.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00028.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/01009.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/00054.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/01014.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/01329.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/16338.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00864.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00363.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/01057.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/01025.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00326.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00830.png
Missing: ../../datasets/CNNSpot/train/car/0_real/08349.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/00462.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00888.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/00372.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/01106.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/15187.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00275.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/01279.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/01124.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/01223.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/00420.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00046.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/01168.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/01228.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00074.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00527.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/01157.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00619.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00149.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/01261.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00767.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/01301.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00944.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/01049.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00480.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/00712.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/09480.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/00532.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00336.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/09409.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00442.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00116.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00038.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00827.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00197.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/01359.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/01253.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/01139.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00242.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00365.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/01176.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00415.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00646.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00573.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00918.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00475.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00215.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00840.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/01366.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/00507.png
Missing: ../../datasets/CNNSpot/train/person/0_real/00817.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00156.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00973.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/01178.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00338.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/01305.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00126.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/00815.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00461.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/00122.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/12216.png
Missing: ../../datasets/CNNSpot/train/person/0_real/00248.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00055.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00760.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00736.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00998.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/01349.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00774.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00282.png
Missing: ../../datasets/CNNSpot/train/train/0_real/01197.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00453.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/01065.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00292.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/01344.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00155.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00598.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/00421.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/17725.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00219.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/01031.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00063.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00269.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00144.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00777.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/00577.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00496.png
Missing: ../../datasets/CNNSpot/train/car/0_real/01093.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/15943.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00434.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00836.png
Missing: ../../datasets/CNNSpot/train/person/0_real/00531.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00943.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/01091.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00802.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00298.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00639.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00971.png
Missing: ../../datasets/CNNSpot/train/person/0_real/00168.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/01264.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/01182.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00054.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00899.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00454.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00667.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/01129.png
Missing: ../../datasets/CNNSpot/train/person/0_real/01298.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00953.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/01058.png
Missing: ../../datasets/CNNSpot/train/person/0_real/07599.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00602.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/01097.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/11025.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00970.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00449.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00856.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00420.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00938.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00281.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/00024.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00871.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/01335.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/00992.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00058.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/01224.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00532.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/01041.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00972.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/01272.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00057.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00212.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00507.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00688.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00199.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/01098.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00842.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00009.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00687.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00384.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00168.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00701.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00474.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00997.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/01238.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/01156.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/01127.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00964.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00630.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00764.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00471.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00973.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00116.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/00157.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00541.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/01202.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/05455.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00606.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/06111.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00082.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00300.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00242.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/00749.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/01193.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00498.png
Missing: ../../datasets/CNNSpot/train/person/0_real/00201.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/05322.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00998.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/01037.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00541.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/01218.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00724.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00376.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/02538.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00936.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00567.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00311.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/01037.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00334.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00336.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00580.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00602.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00609.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00660.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00205.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00124.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/01287.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/00571.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00088.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/01006.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/01355.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00372.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00261.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/03331.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00484.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00687.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/01327.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00447.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00043.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00044.png
Missing: ../../datasets/CNNSpot/train/person/0_real/01290.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00497.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00179.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/01012.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00876.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/00228.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00457.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/01118.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00944.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/01291.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/01227.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/01162.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00762.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00175.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00791.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00661.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/01198.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00846.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00940.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00641.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/01351.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/01150.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00269.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00901.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/01181.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00041.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00346.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00960.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00236.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/00924.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00189.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/01342.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/01007.png
Missing: ../../datasets/CNNSpot/train/person/0_real/01117.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00943.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00971.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00223.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/00339.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/01002.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00683.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00258.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00351.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/00764.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00854.png
Missing: ../../datasets/CNNSpot/train/bird/0_real/00605.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/00730.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/00083.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/03056.png
Missing: ../../datasets/CNNSpot/train/person/0_real/01110.png
Missing: ../../datasets/CNNSpot/train/diningtable/0_real/01016.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00787.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/01117.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00894.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00555.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/01022.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00991.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00906.png
Missing: ../../datasets/CNNSpot/train/car/0_real/01039.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00556.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00301.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00974.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00720.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00954.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/01349.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/00836.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00524.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00217.png
Missing: ../../datasets/CNNSpot/train/pottedplant/0_real/00271.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00563.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00073.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/00725.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00726.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/00740.png
Missing: ../../datasets/CNNSpot/train/airplane/0_real/01266.png
Missing: ../../datasets/CNNSpot/train/bottle/0_real/00780.png
Missing: ../../datasets/CNNSpot/train/person/0_real/00058.png
Missing: ../../datasets/CNNSpot/train/train/0_real/00580.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/00646.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00661.png
Missing: ../../datasets/CNNSpot/train/horse/0_real/01341.png
Missing: ../../datasets/CNNSpot/train/cow/0_real/00686.png
Missing: ../../datasets/CNNSpot/train/sofa/0_real/00410.png
Missing: ../../datasets/CNNSpot/train/sheep/0_real/16192.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00937.png
Missing: ../../datasets/CNNSpot/train/car/0_real/00295.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00154.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/00371.png
Missing: ../../datasets/CNNSpot/train/motorbike/0_real/00605.png
Missing: ../../datasets/CNNSpot/train/bicycle/0_real/00796.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/00676.png
Missing: ../../datasets/CNNSpot/train/cat/0_real/00470.png
Missing: ../../datasets/CNNSpot/train/dog/0_real/00613.png
Missing: ../../datasets/CNNSpot/train/person/0_real/00325.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00767.png
Missing: ../../datasets/CNNSpot/train/chair/0_real/01217.png
Missing: ../../datasets/CNNSpot/train/tvmonitor/0_real/00351.png
Missing: ../../datasets/CNNSpot/train/bus/0_real/00985.png
Missing: ../../datasets/CNNSpot/train/boat/0_real/00717.png

In [30]:
root = Path("../../replication_datasets/CNNSpot")

extensions = {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".webp"}

count = sum(1 for p in root.rglob("*") if p.suffix.lower() in extensions)

print(count)
print(length_CNNSpot_real-18) # there are 18 duplicates

94189
26070

### Fake

In [3]:
CNNSpot_fake = test_generated[test_generated["dataset name"] == "CNNSpot"].copy()

length_CNNSpot_fake = len(CNNSpot_fake)

length_CNNSpot_fake

72590

In [4]:
CNNSpot_fake.head()

                                              path dataset name
0                   stylegan/car/1_fake/008017.png      CNNSpot
1                   train2/person/1_fake/00570.png      CNNSpot
3  cyclegan/orange/1_fake/n07740461_12101_fake.png      CNNSpot
4                      train2/cow/1_fake/01321.png      CNNSpot
5  cyclegan/orange/1_fake/n07740461_14960_fake.png      CNNSpot

In [5]:
split_fake = CNNSpot_fake["path"].str.split(pat="/")

CNNSpot_fake["part0"] = split_fake.str[0]
CNNSpot_fake["part1"] = split_fake.str[1]
CNNSpot_fake["part2"] = split_fake.str[2]
CNNSpot_fake["part3"] = split_fake.str[3]

In [6]:
CNNSpot_fake

,path,dataset name,part0,part1,part2,part3
0,stylegan/car/1_fake/008017.png,CNNSpot,stylegan,car,1_fake,008017.png
1,train2/person/1_fake/00570.png,CNNSpot,train2,person,1_fake,00570.png
3,cyclegan/orange/1_fake/n07740461_12101_fake.png,CNNSpot,cyclegan,orange,1_fake,n07740461_12101_fake.png
4,train2/cow/1_fake/01321.png,CNNSpot,train2,cow,1_fake,01321.png
5,cyclegan/orange/1_fake/n07740461_14960_fake.png,CNNSpot,cyclegan,orange,1_fake,n07740461_14960_fake.png
...,...,...,...,...,...,...
100694,stylegan2/cat/1_fake/001589.png,CNNSpot,stylegan2,cat,1_fake,001589.png
100695,stylegan2/horse/1_fake/001545.png,CNNSpot,stylegan2,horse,1_fake,001545.png
100696,train2/train/1_fake/00997.png,CNNSpot,train2,train,1_fake,00997.png
100698,crn/1_fake/100212_output.png,CNNSpot,crn,1_fake,100212_output.png,NaN
100699,train2/horse/1_fake/00783.png,CNNSpot,train2,horse,1_fake,00783.png

In [7]:
print(CNNSpot_fake.part0.unique())
print(CNNSpot_fake.part1.unique())
print(CNNSpot_fake.part2.unique())
print(CNNSpot_fake.part3.unique())

# ! train2 and the different generators from the test split follow different path structures
# training set: train2/<obejct_name>/0_real/<file_name>
# testing set: <generator_name>/1_fake/<file_name>

['stylegan' 'train2' 'cyclegan' 'imle' 'stylegan2' 'san' 'crn' 'gaugan'
 'biggan']
['car' 'person' 'orange' 'cow' '1_fake' 'airplane' 'church' 'dog' 'bird'
 'chair' 'bottle' 'sofa' 'bicycle' 'summer' 'pottedplant' 'winter' 'sheep'
 'horse' 'cat' 'diningtable' 'motorbike' 'train' 'boat' 'tvmonitor' 'bus'
 'bedroom' 'zebra' 'apple']
['1_fake' '00100639.png' '00100807.png' ... '00100825.png' '00267139.png'
 '000000043435.png']
['008017.png' '00570.png' 'n07740461_12101_fake.png' ... '036150.png'
 '095833.png' '075918.png']

In [8]:
CNNSpot_fake["real_path"] = CNNSpot_fake["path"]

mask_train = CNNSpot_fake["part0"] == "train2"
mask_not_train = CNNSpot_fake["part0"] != "train2"

CNNSpot_fake.loc[mask_train, "real_path"] = (
    CNNSpot_fake.loc[mask_train, "path"]
    .str.replace("^train2/", "CNNSpot/train/", regex=True)
)

CNNSpot_fake.loc[mask_not_train, "real_path"] = (
    "CNNSpot/test/" + CNNSpot_fake.loc[mask_not_train, "path"]
)

In [9]:
CNNSpot_fake

,path,dataset name,part0,part1,part2,part3,real_path
0,stylegan/car/1_fake/008017.png,CNNSpot,stylegan,car,1_fake,008017.png,CNNSpot/test/stylegan/car/1_fake/008017.png
1,train2/person/1_fake/00570.png,CNNSpot,train2,person,1_fake,00570.png,CNNSpot/train/person/1_fake/00570.png
3,cyclegan/orange/1_fake/n07740461_12101_fake.png,CNNSpot,cyclegan,orange,1_fake,n07740461_12101_fake.png,CNNSpot/test/cyclegan/orange/1_fake/n07740461_...
4,train2/cow/1_fake/01321.png,CNNSpot,train2,cow,1_fake,01321.png,CNNSpot/train/cow/1_fake/01321.png
5,cyclegan/orange/1_fake/n07740461_14960_fake.png,CNNSpot,cyclegan,orange,1_fake,n07740461_14960_fake.png,CNNSpot/test/cyclegan/orange/1_fake/n07740461_...
...,...,...,...,...,...,...,...
100694,stylegan2/cat/1_fake/001589.png,CNNSpot,stylegan2,cat,1_fake,001589.png,CNNSpot/test/stylegan2/cat/1_fake/001589.png
100695,stylegan2/horse/1_fake/001545.png,CNNSpot,stylegan2,horse,1_fake,001545.png,CNNSpot/test/stylegan2/horse/1_fake/001545.png
100696,train2/train/1_fake/00997.png,CNNSpot,train2,train,1_fake,00997.png,CNNSpot/train/train/1_fake/00997.png
100698,crn/1_fake/100212_output.png,CNNSpot,crn,1_fake,100212_output.png,NaN,CNNSpot/test/crn/1_fake/100212_output.png
100699,train2/horse/1_fake/00783.png,CNNSpot,train2,horse,1_fake,00783.png,CNNSpot/train/horse/1_fake/00783.png

In [10]:
root = Path("../../datasets/")

CNNSpot_fake["exists"] = [
    (root / p).exists() for p in CNNSpot_fake["real_path"]
]

print(CNNSpot_fake["exists"].value_counts()) # results mean that all file paths exist, within the CNNSpot folder

exists
True     71535
False     1055
Name: count, dtype: int64

In [11]:
pd.set_option("display.max_colwidth", None)

In [12]:
missing = CNNSpot_fake[~CNNSpot_fake["exists"]]

missing["real_path"].head(20)

21      CNNSpot/test/cyclegan/summer/1_fake/2016-01-02 20_15_00_fake.png
28      CNNSpot/test/cyclegan/winter/1_fake/2013-07-22 00_17_40_fake.png
472     CNNSpot/test/cyclegan/winter/1_fake/2016-05-21 00_48_51_fake.png
480     CNNSpot/test/cyclegan/winter/1_fake/2015-06-29 14_59_01_fake.png
495     CNNSpot/test/cyclegan/summer/1_fake/2009-02-20 00_18_51_fake.png
519     CNNSpot/test/cyclegan/winter/1_fake/2012-06-14 05_38_40_fake.png
547     CNNSpot/test/cyclegan/summer/1_fake/2013-03-02 03_57_51_fake.png
611     CNNSpot/test/cyclegan/winter/1_fake/2013-07-12 20_32_51_fake.png
655     CNNSpot/test/cyclegan/winter/1_fake/2013-08-23 20_48_11_fake.png
892     CNNSpot/test/cyclegan/winter/1_fake/2012-05-15 07_40_41_fake.png
893     CNNSpot/test/cyclegan/winter/1_fake/2011-10-12 01_13_31_fake.png
1101    CNNSpot/test/cyclegan/summer/1_fake/2016-01-12 20_58_51_fake.png
1260    CNNSpot/test/cyclegan/summer/1_fake/2010-11-04 16_00_00_fake.png
1484    CNNSpot/test/cyclegan/winter/1_fake/2015-09-12 19_16_51_fake.png
1608    CNNSpot/test/cyclegan/summer/1_fake/2013-06-23 11_12_40_fake.png
1664    CNNSpot/test/cyclegan/winter/1_fake/2013-08-22 00_47_11_fake.png
1760    CNNSpot/test/cyclegan/winter/1_fake/2013-06-25 19_25_21_fake.png
1799    CNNSpot/test/cyclegan/winter/1_fake/2011-08-21 16_52_50_fake.png
1872    CNNSpot/test/cyclegan/winter/1_fake/2014-05-19 05_07_21_fake.png
1923    CNNSpot/test/cyclegan/summer/1_fake/2016-01-05 10_52_21_fake.png
Name: real_path, dtype: object

In [13]:
len(CNNSpot_fake[
    CNNSpot_fake["part1"].isin(["summer", "winter"])
])

1055

In [14]:
mask = CNNSpot_fake["part1"].isin(["summer", "winter"])

CNNSpot_fake.loc[mask, "real_path"] = CNNSpot_fake.loc[mask, "real_path"].str.replace(
    r'(\d{2})_(\d{2})_(\d{2})(_[^/]+$)',
    r'\1:\2:\3\4',
    regex=True
)

In [15]:
root = Path("../../datasets/")

CNNSpot_fake["exists"] = [
    (root / p).exists() for p in CNNSpot_fake["real_path"]
]

print(CNNSpot_fake["exists"].value_counts()) # results mean that all file paths exist, within the CNNSpot folder

exists
True    72590
Name: count, dtype: int64

In [16]:
duplicates_CNN_fake = CNNSpot_fake.real_path[CNNSpot_fake.real_path.duplicated()]
(f"Number of duplicate paths: {len(duplicates_CNN_fake)}")

'Number of duplicate paths: 4471'

In [17]:
duplicates_CNN_fake = CNNSpot_fake.path[CNNSpot_fake.path.duplicated()]
(f"Number of duplicate paths: {len(duplicates_CNN_fake)}")

'Number of duplicate paths: 4471'

In [18]:
src_root = Path("../../datasets")      # where files currently are
dst_root = Path("../../replication_datasets")   # where you want them

for rel_path in CNNSpot_fake["real_path"]:
    src = src_root / rel_path
    dst = dst_root / rel_path

    if src.exists():
        dst.parent.mkdir(parents=True, exist_ok=True)  # create folders
        shutil.copy2(src, dst)  # preserves metadata
    else:
        print(f"Missing: {src}")

In [22]:
root = Path("../../replication_datasets/CNNSpot")

extensions = {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".webp"}

count = sum(1 for p in root.rglob("*") if p.suffix.lower() in extensions)

print(count)
print(length_CNNSpot_real - 18 + length_CNNSpot_fake - 4471)

94189
94189

## GenImage